name: shop_ease
description: "ShopEase - offline-first shopping app built with Flutter + Firebase."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0

  # State, storage, connectivity
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  connectivity_plus: ^7.3.1

  # Utils
  uuid: ^4.5.1
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  cached_network_image: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/
